### ISSUE TITLE
publish new version

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/plugin#6]
@bwilkerson, can you publish a new version?

**Comment by bwilkerson** [comment]
Sure. The version number in `pubspec.yaml` is currently `0.2.0+1` (with the last published version at `0.2.0`). Is that the version number you want to publish, or should we bump the version number first?

**Comment by devoncarew** [comment]
Publishing as is sgtm :)

**Comment by bwilkerson** [comment]
Done.
